fw-shipped-$(CONFIG_WILC) += microchip/wilc3000_ble_firmware.bin
fw-shipped-$(CONFIG_WILC) += microchip/wilc3000_ble_firmware_no_rtc.bin
fw-shipped-$(CONFIG_WILC) += microchip/wilc3000_wifi_firmware.bin
fw-shipped-$(CONFIG_WILC) += microchip/wilc3000_wifi_firmware_ua.bin
